[tool.poetry]
name = "sam_workflows"
version = "0.3.0"
description = "Workflows for SAM used at Aarhus City Archives"
authors = ["Claus Juhl Knudsen <cjk@aarhus.dk>", "Nina Jensen <jnik@aarhus.dk>"]
maintainers = ["Aarhus Stadsarkiv <stadsarkiv@aarhus.dk>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://www.aarhusstadsarkiv.dk/"

[tool.poetry.dependencies]
python = "~3.8"
gooey = "^1.0.8"
natsort = "^7.1.1"
pyinstaller = "^4.2"
pymupdf = "^1.18.12"
azure-identity = "^1.5.0"
azure-keyvault-secrets = "^4.2.0"
azure-storage-blob = "^12.8.0"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^2.11"
black = "^20.8b1"
flake8 = "^3.9.0"
mypy = "^0.812"

[tool.black]
line-length = 79
exclude = ".venv"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
